export const productsDetailArray = [
  {
    id: "1",
    productName: "Wireless Mouse",
    productDescription: "Ergonomic wireless mouse with adjustable DPI.",
    price: 25.99,
    quantity: 100,
    category: "Electronics",
    categoryId: "1",
  },
  {
    id: "2",
    productName: "Bluetooth Headphones",
    productDescription:
      "Noise-cancelling over-ear headphones with long battery life.",
    price: 89.99,
    quantity: 50,
    category: "Electronics",
    categoryId: "1",
  },
  {
    id: "3",
    productName: "Gaming Keyboard",
    productDescription: "Mechanical keyboard with RGB backlighting.",
    price: 79.99,
    quantity: 75,
    category: "Electronics",
    categoryId: "1",
  },
  {
    id: "4",
    productName: "Smartphone Stand",
    productDescription: "Adjustable stand for smartphones and tablets.",
    price: 15.99,
    quantity: 200,
    category: "Accessories",
    categoryId: "11",
  },
  {
    id: "5",
    productName: "USB-C Hub",
    productDescription: "Multi-port USB-C hub with HDMI and Ethernet.",
    price: 49.99,
    quantity: 150,
    category: "Electronics",
    categoryId: "1",
  },
  {
    id: "6",
    productName: "Portable Charger",
    productDescription: "High-capacity portable charger with fast charging.",
    price: 39.99,
    quantity: 120,
    category: "Accessories",
    categoryId: "11",
  },
  {
    id: "7",
    productName: "Fitness Tracker",
    productDescription: "Waterproof fitness tracker with heart rate monitor.",
    price: 59.99,
    quantity: 80,
    category: "Wearables",
    categoryId: "12",
  },
  {
    id: "8",
    productName: "Smart Light Bulb",
    productDescription: "Wi-Fi enabled smart light bulb with color changing.",
    price: 19.99,
    quantity: 300,
    category: "Home",
    categoryId: "13",
  },
  {
    id: "9",
    productName: "Laptop Sleeve",
    productDescription: "Protective laptop sleeve with extra pockets.",
    price: 29.99,
    quantity: 90,
    category: "Accessories",
    categoryId: "11",
  },
  {
    id: "10",
    productName: "Wireless Charger",
    productDescription: "Fast wireless charger for smartphones.",
    price: 24.99,
    quantity: 110,
    category: "Electronics",
    categoryId: "1",
  },
  {
    id: "11",
    productName: "Smart Thermostat",
    productDescription: "Energy-saving smart thermostat with remote control.",
    price: 129.99,
    quantity: 60,
    category: "Home",
    categoryId: "13",
  },
  {
    id: "12",
    productName: "Bluetooth Speaker",
    productDescription: "Portable Bluetooth speaker with deep bass.",
    price: 45.99,
    quantity: 140,
    category: "Electronics",
    categoryId: "1",
  },
  {
    id: "13",
    productName: "Action Camera",
    productDescription: "4K action camera with waterproof case.",
    price: 99.99,
    quantity: 70,
    category: "Cameras",
    categoryId: "14",
  },
  {
    id: "14",
    productName: "Electric Kettle",
    productDescription: "Stainless steel electric kettle with auto shut-off.",
    price: 34.99,
    quantity: 130,
    category: "Home",
    categoryId: "13",
  },
  {
    id: "15",
    productName: "Smartwatch",
    productDescription: "Smartwatch with fitness tracking and notifications.",
    price: 199.99,
    quantity: 40,
    category: "Wearables",
    categoryId: "12",
  },
];
